from time import sleep
from os import system
def menu():
        print("""
        __   __          ____
        \ \ / /__  _   _|  _ \  _____      __
         \ V / _ \| | | | | | |/ _ \ \ /\ / /
          | | (_) | |_| | |_| | (_) \ V  V /
          |_|\___/ \__,_|____/ \___/ \_/\_/
                <==================>
                   [1] Videos
                   [2] Musica
                   [3] PlayList
                   [4] Enter (sair)
                <==================>
        """)
def loop():
	while True:
	        system("clear")
	        print("Iniciando", end="")
	        print(".")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando", end="")
	        print("..")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando", end="")
	        print("...")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando", end="")
	        print(".")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando", end="")
	        print("..")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando", end="")
	        print("...")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando", end="")
	        print(".")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando", end="")
	        print("..")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando", end="")
	        print("...")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando", end="")
	        print(".")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando", end="")
	        print("..")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando", end="")
	        print("...")
	        sleep (0.3)
	        system("clear")
	        break

def baixa():
	while True:
	        system("clear")
	        print("Iniciando Downloads", end="")
	        print(".")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando Downloads", end="")
	        print("..")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando Downloads", end="")
	        print("...")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando Downloads", end="")
	        print(".")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando Downloads", end="")
	        print("..")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando Downloads", end="")
	        print("...")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando Downloads", end="")
	        print(".")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando Downloads", end="")
	        print("..")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando Downloads", end="")
	        print("...")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando Downloads", end="")
	        print(".")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando Downloads", end="")
	        print("..")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando Downloads", end="")
	        print("...")
	        sleep (0.3)
	        print("Iniciando Downloads", end="")
	        print(".")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando Downloads", end="")
	        print("..")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando Downloads", end="")
	        print("...")
	        sleep (0.3)
	        system("clear")
	        print("Iniciando Downloads", end="")
	        print(".")
	        sleep(0.3)
	        system("clear")
	        print("Iniciando Downloads", end="")
	        print("..")
	        sleep(0.3)
	        system("clear")
	        print("Iniciando Downloads", end="")
	        print("...")
	        sleep(0.3)
	        system("clear")
	        print("Aguardem!")
	        break
